version: '3.9'

services:
  database:
    image: postgres
    container_name: crud-react
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=database
    volumes:
      - pgdata:/dta/postgres

volumes:
  pgdata:
    driver: local